# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "library_ils"
primary_region = "iad"

[build]
     image = "python:3.11.9"  # Choose your desired Python version
     command = "pip install -r requirements.txt"  # Install dependencies

[processes]
     app = "gunicorn main:app -w 4 -b 0.0.0.0:8080"  # Assuming you're using Gunicorn
